### PR TITLE
[ADD] tests gtin code

### PR DESCRIPTION
**Pull request by JehoG**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Is this PR going towards the source (camptocamp/c2c-rd-addons)

**Comment by JehoG** [comment]
Yes, here's the PR:
https://github.com/camptocamp/c2c-rd-addons/pull/4
Hum, ya, should I close this one and wait for them to merge?

**Comment by bwrsandman** [comment]
Yes and if they don't get back to you quickly enough, you may need to contact them by email.

**Comment by JehoG** [comment]
Ok, closing

**Pull request closed without merging**
